import { Client } from "pg";
import type { NodeExecutor } from "./node_context.schema";
import type { PostgresNodeData } from "./node-data.types";
import { prisma } from "../../lib/prisma";

export const executePostgres: NodeExecutor = async (node, context) => {
  const data = node.data as PostgresNodeData;

  if (!data.credentialId) {
    throw new Error("PostgreSQL credential is required");
  }

  // Find the node connected to PostgreSQL
  const connection = context.connections.find(
    (connection) => connection.toNodeId === node.id,
  );

  if (!connection) {
    throw new Error("PostgreSQL node has no input connection");
  }

  // Get the previous node's result
  const previousResult = context.results[connection.fromNodeId];

  if (!previousResult) {
    throw new Error("Previous node did not return any result");
  }

  // AI executor returns:
  // {
  //   response: "INSERT INTO users (name, age) VALUES ('Adarsh', 23)"
  // }
  const query = previousResult.response;

  if (typeof query !== "string" || !query.trim()) {
    throw new Error("Previous node did not return a SQL query");
  }

  // Get user's PostgreSQL credentials
  const credential = await prisma.credential.findUnique({
    where: {
      id: data.credentialId,
    },
  });

  if (!credential) {
    throw new Error("PostgreSQL credential not found");
  }

  const config = JSON.parse(credential.value);

  const client = new Client({
    host: config.host,
    port: config.port,
    database: config.database,
    user: config.username,
    password: config.password,
    ssl: config.ssl
      ? {
          rejectUnauthorized: false,
        }
      : undefined,
  });

  try {
    await client.connect();

    // Execute SQL generated by the previous AI node
    const result = await client.query(query);

    return {
      query,
      rows: result.rows,
      rowCount: result.rowCount,
    };
  } finally {
    await client.end();
  }
};
