export enum NodeType {
  OPENAI = "OPENAI",
  GEMINI = "GEMINI",
  SLACK = "SLACK",
  MANUAL_TRIGGER = "MANUAL TRIGGER",
  WEBHOOK = "WEBHOOK",
  HTTP_TRIGGER = "HTTP TRIGGER",
  EMAIL = "EMAIL",
  POSTGRES = "POSTGRES",
  OUTPUT = "OUTPUT",
  TEXT = "TEXT",
  GOOGLE_FORM = "GOOGLE_FORM",
  HTTP_REQUEST = "HTTP_REQUEST",
}
