export enum NodeType {
  INPUT_TRIGGER = "INPUT_TRIGGER",
  BROWSER_TRIGGER = "BROWSER_TRIGGER",
  HTTP_TRIGGER = "HTTP_TRIGGER",
  WEBHOOK_TRIGGER = "WEBHOOK_TRIGGER",
  OUTPUT = "OUTPUT",
  CLAUDE_EXECUTER="CLAUDE",
  OPENAI_EXECUTER = "OPENAI",
  GEMINI_EXECUTER = "GEMINI",
  POSTGRES_EXECUTER = "POSTGRES",
  EMAIL_EXECUTER = "EMAIL",
  SLACK_EXECUTER = "SLACK",
  GOOGLE_FORM_EXECUTER = "GOOGLE_FORM",
}
